---
- name: Install netdata
  xbps:
    pkg: netdata
    state: present

- name: Enable netdata
  runit:
    name: netdata
    enabled: yes
    state: started

- name: Install firewall rules
  copy:
    src: netdata.rules
    dest: /etc/iptables.d/netdata.rules
    owner: root
    group: root
    mode: 0640
  notify:
    - iptables
